spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
#    host: 192.168.142.128
    host: 192.168.73.128
    # Redis服务器连接端口
    port: 6379  #6379
    # Redis 密码
    password: chen123456
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 10000
    #ElasticSearch配置
  elasticsearch:
    rest:
      uris: http://192.168.73.128:9200
